Play travis
Otus-DevOps-2021-05/zagretdinov-d_infra pull request #1
Opened 2021-06-16 23:34 UTC by zagretdinov-d

2021-06-17 18:03 UTC, mrgreyves requested changes
Здравствуйте!) Вам стоит свериться с методическим указанием, не хватает некоторых файлов. ДЗ возвращаю на доработку.

2021-06-20 23:43 UTC, zagretdinov-d commented
Здравствуйте) Это ДЗ можете проверить?

2021-06-21 16:42 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к файлу. ДЗ возвращаю на доработку.

2021-06-21 16:42 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Обратите внимание на этот файл =)

2021-06-22 06:35 UTC, zagretdinov-d commented
Здравствуйте). Проверте пожалуйста ДЗ файлик исправил.

2021-06-23 08:10 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-06-25 08:01 UTC, merged