Cloud bastion
Otus-DevOps-2021-05/zagretdinov-d_infra pull request #2
Opened 2021-06-20 23:37 UTC by zagretdinov-d

2021-06-21 16:41 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Стоит добавить описание к ридми файлу.
![image](https://user-images.githubusercontent.com/34331259/122797890-a183e580-d2c8-11eb-9516-c937ab570b2d.png)
Так же вам стоит свериться с методичкой и указать адреса хостов как указано в методичке. ДЗ возвращаю на доработку.

2021-06-22 06:41 UTC, zagretdinov-d commented
Здравствуйте) исправлении провел проверьте пожалуйста)

2021-06-23 08:15 UTC, mrgreyves requested changes
Здравствуйте!) Вам следует свериться с результатами тестов, там описаны все проблемы. ДЗ возвращаю на доработку.

2021-06-23 08:15 UTC, mrgreyves commented on README.md
> +## bastion_IP = 84.201.158.166
Вот тут ошибка, не нужно перед адресами ставить #

2021-06-24 18:19 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-06-25 08:01 UTC, merged